### ISSUE TITLE
先精神上支持一下，后面或许会行动上支持。

### ISSUE THREAD

**Issue by yuyenews** [Snailclimb/guide-rpc-framework#1]
我自己 有一个Rest风格的分布式中间件，主要是用来补充Mars-Java的开源生态的。但是RPC的还没有，我先了解一下，后续或许会专门为这个项目开发一个starter。

**Comment by Snailclimb** [comment]
> 我自己 有一个Rest风格的分布式中间件，主要是用来补充Mars-Java的开源生态的。但是RPC的还没有，我先了解一下，后续或许会专门为这个项目开发一个starter。

期待~~~
