### ISSUE TITLE
为什么不用@Autowired注解获取单例

### ISSUE THREAD

**Issue by AdmireAn** [Snailclimb/guide-rpc-framework#17]
很多地方使用了github.javaguide.factory.SingletonFactory获取单例bean
为什么不用@Autowired，Spring不是天然支持单例吗

**Comment by Snailclimb** [comment]
> 很多地方使用了github.javaguide.factory.SingletonFactory获取单例bean
> 为什么不用@Autowired，Spring不是天然支持单例吗

因为最开始写这个的时候，没有想到用 Spring，然后也不想太依赖Spring。目前只是用Spring扫描注册一下自定义注解。

**Comment by hutaishi** [comment]
对于一些中间件可以考虑：中间件不依赖spring，然后spring boot starter依赖spring并作自动配置。
扫描自定义注解可以不用依赖spring

**Comment by Snailclimb** [comment]
> 对于一些中间件可以考虑：中间件不依赖spring，然后spring boot starter依赖spring并作自动配置。
> 扫描自定义注解可以不用依赖spring

嗯嗯 这个最近会有改动。
