### ISSUE TITLE
关于 SingletonFactory 获取单例的问题

### ISSUE THREAD

**Issue by 1228857713** [Snailclimb/guide-rpc-framework#30]
https://github.com/Snailclimb/guide-rpc-framework/blob/master/rpc-framework-common/src/main/java/github/javaguide/factory/SingletonFactory.java

```java
public static <T> T getInstance(Class<T> c) {
        String key = c.toString();
        Object instance = null;
        if (instance == null) {
            synchronized (SingletonFactory.class) {
                instance = OBJECT_MAP.get(key);
                if (instance == null) {
                    try {
                        instance = c.getDeclaredConstructor().newInstance();
                        OBJECT_MAP.put(key, instance);
                    } catch (IllegalAccessException | InstantiationException e) {
                        throw new RuntimeException(e.getMessage(), e);
                    } catch (NoSuchMethodException | InvocationTargetException e) {
                        e.printStackTrace();
                    }
                }
            }
        }

        return c.cast(instance);
    }
```

这一段感觉在模仿标准的 dcl 写法，但是 
```java
Object instance = null;
if (instance == null) {
synchronized (SingletonFactory.class) {
```
明显 instance 肯定为空，判断多余，且synchronized (SingletonFactory.class) {   使用 类锁，锁的力度很大，在多线程情况下并发度很低阻塞会很严重

**Comment by 1228857713** [comment]
![image](https://user-images.githubusercontent.com/17972781/100311443-bf1af600-2fea-11eb-820f-f97de9424fcb.png)

标准的dcl 会添加 volatile 关键词来防止 指令重排， 这里 instance 指令增加了volatile 可以防止以下两个指令重排序的问题导致其他线程拿到了 instance 对象，而该对象确没有完成实例化

**Comment by 1228857713** [comment]
不知道在上述情况下是否需要 添加 volatile 来防止上述问题
![image](https://user-images.githubusercontent.com/17972781/100312272-d824a680-2fec-11eb-9b0d-32ba6f127f3e.png)

请大神解答以下我的疑惑

**Comment by javaguide-tech** [comment]
> https://github.com/Snailclimb/guide-rpc-framework/blob/master/rpc-framework-common/src/main/java/github/javaguide/factory/SingletonFactory.java
> 
> ```java
> public static <T> T getInstance(Class<T> c) {
>         String key = c.toString();
>         Object instance = null;
>         if (instance == null) {
>             synchronized (SingletonFactory.class) {
>                 instance = OBJECT_MAP.get(key);
>                 if (instance == null) {
>                     try {
>                         instance = c.getDeclaredConstructor().newInstance();
>                         OBJECT_MAP.put(key, instance);
>                     } catch (IllegalAccessException | InstantiationException e) {
>                         throw new RuntimeException(e.getMessage(), e);
>                     } catch (NoSuchMethodException | InvocationTargetException e) {
>                         e.printStackTrace();
>                     }
>                 }
>             }
>         }
> 
>         return c.cast(instance);
>     }
> ```
> 
> 这一段感觉在模仿标准的 dcl 写法，但是
> 
> ```java
> Object instance = null;
> if (instance == null) {
> synchronized (SingletonFactory.class) {
> ```
> 
> 明显 instance 肯定为空，判断多余，且synchronized (SingletonFactory.class) { 使用 类锁，锁的力度很大，在多线程情况下并发度很低阻塞会很严重

这里直接把最外层判断 instance 对象是否为空给移除就可以了吧！

**Comment by 1228857713** [comment]
> > https://github.com/Snailclimb/guide-rpc-framework/blob/master/rpc-framework-common/src/main/java/github/javaguide/factory/SingletonFactory.java
> > ```java
> > public static <T> T getInstance(Class<T> c) {
> >         String key = c.toString();
> >         Object instance = null;
> >         if (instance == null) {
> >             synchronized (SingletonFactory.class) {
> >                 instance = OBJECT_MAP.get(key);
> >                 if (instance == null) {
> >                     try {
> >                         instance = c.getDeclaredConstructor().newInstance();
> >                         OBJECT_MAP.put(key, instance);
> >                     } catch (IllegalAccessException | InstantiationException e) {
> >                         throw new RuntimeException(e.getMessage(), e);
> >                     } catch (NoSuchMethodException | InvocationTargetException e) {
> >                         e.printStackTrace();
> >                     }
> >                 }
> >             }
> >         }
> > 
> >         return c.cast(instance);
> >     }
> > ```
> > 
> > 
> > 这一段感觉在模仿标准的 dcl 写法，但是
> > ```java
> > Object instance = null;
> > if (instance == null) {
> > synchronized (SingletonFactory.class) {
> > ```
> > 
> > 
> > 明显 instance 肯定为空，判断多余，且synchronized (SingletonFactory.class) { 使用 类锁，锁的力度很大，在多线程情况下并发度很低阻塞会很严重
> 
> 这里直接把最外层判断 instance 对象是否为空给移除就可以了吧！

这不行把，那所有的对象获取，都会进入锁竞争嘛。那效率就会很低

**Comment by Snailclimb** [comment]
> > > https://github.com/Snailclimb/guide-rpc-framework/blob/master/rpc-framework-common/src/main/java/github/javaguide/factory/SingletonFactory.java
> > > ```java
> > > public static <T> T getInstance(Class<T> c) {
> > >         String key = c.toString();
> > >         Object instance = null;
> > >         if (instance == null) {
> > >             synchronized (SingletonFactory.class) {
> > >                 instance = OBJECT_MAP.get(key);
> > >                 if (instance == null) {
> > >                     try {
> > >                         instance = c.getDeclaredConstructor().newInstance();
> > >                         OBJECT_MAP.put(key, instance);
> > >                     } catch (IllegalAccessException | InstantiationException e) {
> > >                         throw new RuntimeException(e.getMessage(), e);
> > >                     } catch (NoSuchMethodException | InvocationTargetException e) {
> > >                         e.printStackTrace();
> > >                     }
> > >                 }
> > >             }
> > >         }
> > > 
> > >         return c.cast(instance);
> > >     }
> > > ```
> > > 
> > > 
> > > 这一段感觉在模仿标准的 dcl 写法，但是
> > > ```java
> > > Object instance = null;
> > > if (instance == null) {
> > > synchronized (SingletonFactory.class) {
> > > ```
> > > 
> > > 
> > > 明显 instance 肯定为空，判断多余，且synchronized (SingletonFactory.class) { 使用 类锁，锁的力度很大，在多线程情况下并发度很低阻塞会很严重
> > 
> > 
> > 这里直接把最外层判断 instance 对象是否为空给移除就可以了吧！
> 
> 这不行把，那所有的对象获取，都会进入锁竞争嘛。那效率就会很低
