### ISSUE TITLE
发现的小问题

### ISSUE THREAD

**Issue by guardwarm** [Snailclimb/guide-rpc-framework#37]
![image](https://user-images.githubusercontent.com/48593960/111063508-ec33db80-84e9-11eb-9e41-d786c6428ccb.png)
这个字节数组输出流不需要关闭么？感觉应该写到try后面的括号里

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/48593960/111063508-ec33db80-84e9-11eb-9e41-d786c6428ccb.png)
> 这个字节数组输出流不需要关闭么？感觉应该写到try后面的括号里

已改。
