### ISSUE TITLE
关于加载gzip扩展的一个小错误

### ISSUE THREAD

**Issue by luwanglin** [Snailclimb/guide-rpc-framework#44]
下载最新的代码，运行之后报错如下
![image](https://user-images.githubusercontent.com/34809270/122361362-c1926c80-cf89-11eb-8588-fa5102aa3125.png)
---
发现rpc-framework-simple下面的MERA-INF中关于Compress的配置文件名称写错了，因为`github.javaguide.compress.Compress`接口是大写字母开头的，而配置文件名称是小写字母c所以导致找不到这个接口的SPI扩展类gzip

**Comment by Snailclimb** [comment]
> ## 下载最新的代码，运行之后报错如下
> ![image](https://user-images.githubusercontent.com/34809270/122361362-c1926c80-cf89-11eb-8588-fa5102aa3125.png)
> 发现rpc-framework-simple下面的MERA-INF中关于Compress的配置文件名称写错了，因为`github.javaguide.compress.Compress`接口是大写字母开头的，而配置文件名称是小写字母c所以导致找不到这个接口的SPI扩展类gzip

已经修正👍
