### ISSUE TITLE
github.javaguide.provider.impl.ZkServiceProviderImpl类中为什么有serviceMap，还需要registeredService这个set去保存接口名？

### ISSUE THREAD

**Issue by winterliu1020** [Snailclimb/guide-rpc-framework#46]
请问github.javaguide.provider.impl.ZkServiceProviderImpl类中为什么有serviceMap，还需要registeredService这个set去保存接口名？
```java
/**
     * key: rpc service name(interface name + version + group)
     * value: service object
     */
    private final Map<String, Object> serviceMap;
    private final Set<String> registeredService;

    // 在get方法中：
    String rpcServiceName = rpcServiceConfig.getRpcServiceName();
    if (registeredService.contains(rpcServiceName)) {
        return;
    }
    registeredService.add(rpcServiceName);
    serviceMap.put(rpcServiceName, rpcServiceConfig.getService());
```
直接用serviceMap.containsKey(rpcServiceName)不行吗？对此有些疑惑 :-)

**Comment by Snailclimb** [comment]
> 请问github.javaguide.provider.impl.ZkServiceProviderImpl类中为什么有serviceMap，还需要registeredService这个set去保存接口名？
> 
> ```java
> /**
>      * key: rpc service name(interface name + version + group)
>      * value: service object
>      */
>     private final Map<String, Object> serviceMap;
>     private final Set<String> registeredService;
> 
>     // 在get方法中：
>     String rpcServiceName = rpcServiceConfig.getRpcServiceName();
>     if (registeredService.contains(rpcServiceName)) {
>         return;
>     }
>     registeredService.add(rpcServiceName);
>     serviceMap.put(rpcServiceName, rpcServiceConfig.getService());
> ```
> 
> 直接用serviceMap.containsKey(rpcServiceName)不行吗？对此有些疑惑 :-)

我也有点忘啦，好像是因为 concurrenthashmap 没有你说的这个方法。
