### ISSUE TITLE
请问自定义RPC协议的设计思路是如何？

### ISSUE THREAD

**Issue by damao33** [Snailclimb/guide-rpc-framework#51]
codec包中的编码器解码器是根据这个自定义协议设计的，那这个自定义协议如果让我自己设计，思路应该是怎样的？字段、长度等方面的考量

指的是以下部分
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
+-----+-----+-----+-----+--------+----+----+----+------+-----------+-------+----- --+-----+-----+-------+
| magic code |version | full length | messageType| codec|compress| RequestId |
+-----------------------+--------+---------------------+-----------+-----------+-----------+------------+
| |
| body |
| |
| ... ... |
+-------------------------------------------------------------------------------------------------------+
这个部分 这里没有对齐请谅解

**Comment by Snailclimb** [comment]
> codec包中的编码器解码器是根据这个自定义协议设计的，那这个自定义协议如果让我自己设计，思路应该是怎样的？字段、长度等方面的考量
> 
> 指的是以下部分
> 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
> +-----+-----+-----+-----+--------+----+----+----+------+-----------+-------+----- --+-----+-----+-------+
> | magic code |version | full length | messageType| codec|compress| RequestId |
> +-----------------------+--------+---------------------+-----------+-----------+-----------+------------+
> | |
> | body |
> | |
> | ... ... |
> +-------------------------------------------------------------------------------------------------------+
> 这个部分 这里没有对齐请谅解

这个根据自己的需求进行设计即可，你还可以参考一下 Dubbo 的设计。
