### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [Snailclimb/guide-rpc-framework#7]
hi，Snailclimb，我们对您分享的这个教程十分感兴趣，您的专业技术十分出色，我们想与您进行商务合作，可否在此留下您的邮箱或微信，方便我们与您建立联系呢？

**Comment by Snailclimb** [comment]
> hi，Snailclimb，我们对您分享的这个教程十分感兴趣，您的专业技术十分出色，我们想与您进行商务合作，可否在此留下您的邮箱或微信，方便我们与您建立联系呢？

暂时没有意向哈！
