### ISSUE TITLE
个人觉得提供若干个演化版本更有利于新人学习

### ISSUE THREAD

**Issue by yxyx2019** [Snailclimb/guide-rpc-framework#8]
看到作者说最开始使用BIO（Socket），那么如果能够提供一个最简单的版本，没有使用Zookeeper、Spring、负载均衡这些，初学者能够看得更明白，也更能够明白RPC的本质

**Comment by Snailclimb** [comment]
> 看到作者说最开始使用BIO（Socket），那么如果能够提供一个最简单的版本，没有使用Zookeeper、Spring、负载均衡这些，初学者能够看得更明白，也更能够明白RPC的本质
